//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.BarcodeScanner.Calibration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.BarcodeScanner.Calibration.Properties.Advice", typeof(Advice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Adv_ice_278 {
            get {
                return ResourceManager.GetString("Adv ice_278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to enter data manually into your software for barcodes that contain data formatted according to ISO/IEC 15434 characters..
        /// </summary>
        internal static string Advice_105 {
            get {
                return ResourceManager.GetString("Advice_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience problems when scanning barcodes that contain Format 05 or Format 06 data, enter data manually into your software. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_110 {
            get {
                return ResourceManager.GetString("Advice_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your software for barcodes that contain Format 05 or Format 06 data. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_115 {
            get {
                return ResourceManager.GetString("Advice_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to transmit AIM identifiers. If you have problems when transmitting AIM identifiers, revert to the current configuration..
        /// </summary>
        internal static string Advice_200 {
            get {
                return ResourceManager.GetString("Advice_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may want to switch off Caps Lock and test again..
        /// </summary>
        internal static string Advice_205 {
            get {
                return ResourceManager.GetString("Advice_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configurations and reconfigure them if necessary.;;You may want to switch off Caps Lock and test again..
        /// </summary>
        internal static string Advice_206 {
            get {
                return ResourceManager.GetString("Advice_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may want to switch Caps Lock off..
        /// </summary>
        internal static string Advice_210 {
            get {
                return ResourceManager.GetString("Advice_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to transmit end-of-line sequences and test again. If you have problems when transmitting end-of-line sequences, revert to the current configuration..
        /// </summary>
        internal static string Advice_215 {
            get {
                return ResourceManager.GetString("Advice_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems scanning barcode data, configure your barcode scanner so that it does not transmit a prefix..
        /// </summary>
        internal static string Advice_220 {
            get {
                return ResourceManager.GetString("Advice_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems scanning barcode data, configure your barcode scanner so that it does not transmit any suffix..
        /// </summary>
        internal static string Advice_225 {
            get {
                return ResourceManager.GetString("Advice_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_230 {
            get {
                return ResourceManager.GetString("Advice_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_231 {
            get {
                return ResourceManager.GetString("Advice_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that your barcode scanner is configured to transmit AIM identifiers..
        /// </summary>
        internal static string Advice_232 {
            get {
                return ResourceManager.GetString("Advice_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad and transmit AIM identifiers..
        /// </summary>
        internal static string Advice_235 {
            get {
                return ResourceManager.GetString("Advice_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience problems when scanning barcodes that contain Format 05 or Format 06 data, enter data manually into your software. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_240 {
            get {
                return ResourceManager.GetString("Advice_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your software for barcodes that contain Format 05 or Format 06 data. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_241 {
            get {
                return ResourceManager.GetString("Advice_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your software for barcodes that contain Format 05 or Format 06 data. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_245 {
            get {
                return ResourceManager.GetString("Advice_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you expect to scan barcodes that contain data formatted according to ISO/IEC 15434, run the test again, this time including the ISO/IEC 15434 data compatibility test..
        /// </summary>
        internal static string Advice_250 {
            get {
                return ResourceManager.GetString("Advice_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, check the configuration of your barcode scanner. Look for settings that will improve keyboard entry performance..
        /// </summary>
        internal static string Advice_255 {
            get {
                return ResourceManager.GetString("Advice_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, check the configuration of your barcode scanner. Look for settings that will improve keyboard entry performance..
        /// </summary>
        internal static string Advice_256 {
            get {
                return ResourceManager.GetString("Advice_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan other barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_260 {
            get {
                return ResourceManager.GetString("Advice_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan other barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_261 {
            get {
                return ResourceManager.GetString("Advice_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan other barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_265 {
            get {
                return ResourceManager.GetString("Advice_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan EDI barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_270 {
            get {
                return ResourceManager.GetString("Advice_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan EDI barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_271 {
            get {
                return ResourceManager.GetString("Advice_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan EDI barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_275 {
            get {
                return ResourceManager.GetString("Advice_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_276 {
            get {
                return ResourceManager.GetString("Advice_276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_277 {
            get {
                return ResourceManager.GetString("Advice_277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_278 {
            get {
                return ResourceManager.GetString("Advice_278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_279 {
            get {
                return ResourceManager.GetString("Advice_279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_280 {
            get {
                return ResourceManager.GetString("Advice_280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience difficulty when scanning barcodes, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_281 {
            get {
                return ResourceManager.GetString("Advice_281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode(s)..
        /// </summary>
        internal static string Advice_300 {
            get {
                return ResourceManager.GetString("Advice_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode..
        /// </summary>
        internal static string Advice_301 {
            get {
                return ResourceManager.GetString("Advice_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.;;Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_303 {
            get {
                return ResourceManager.GetString("Advice_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode(s)..
        /// </summary>
        internal static string Advice_304 {
            get {
                return ResourceManager.GetString("Advice_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode.;;If you are asked to scan multiple barcodes, make sure you scan them in the correct order..
        /// </summary>
        internal static string Advice_305 {
            get {
                return ResourceManager.GetString("Advice_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        internal static string Advice_306 {
            get {
                return ResourceManager.GetString("Advice_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your software cannot compensate, configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_307 {
            get {
                return ResourceManager.GetString("Advice_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_308 {
            get {
                return ResourceManager.GetString("Advice_308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your software cannot compensate, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_309 {
            get {
                return ResourceManager.GetString("Advice_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_310 {
            get {
                return ResourceManager.GetString("Advice_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_315 {
            get {
                return ResourceManager.GetString("Advice_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_316 {
            get {
                return ResourceManager.GetString("Advice_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your software cannot compensate, configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_320 {
            get {
                return ResourceManager.GetString("Advice_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Caps Lock off and test again.;;If you must keep Caps Lock switched on while scanning barcodes, you may be able to configure your barcode scanner to compensate..
        /// </summary>
        internal static string Advice_325 {
            get {
                return ResourceManager.GetString("Advice_325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Caps Lock off and test again..
        /// </summary>
        internal static string Advice_326 {
            get {
                return ResourceManager.GetString("Advice_326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary.;;Switch off Caps Lock and test again..
        /// </summary>
        internal static string Advice_327 {
            get {
                return ResourceManager.GetString("Advice_327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary.;;Switch off Caps Lock and test again..
        /// </summary>
        internal static string Advice_328 {
            get {
                return ResourceManager.GetString("Advice_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your scanner, keyboard and computer configuration and reconfigure them if necessary. .
        /// </summary>
        internal static string Advice_330 {
            get {
                return ResourceManager.GetString("Advice_330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary..
        /// </summary>
        internal static string Advice_331 {
            get {
                return ResourceManager.GetString("Advice_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary..
        /// </summary>
        internal static string Advice_332 {
            get {
                return ResourceManager.GetString("Advice_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If possible, configure your computer to use a different keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        internal static string Advice_335 {
            get {
                return ResourceManager.GetString("Advice_335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        internal static string Advice_390 {
            get {
                return ResourceManager.GetString("Advice_390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads most barcodes reliably..
        /// </summary>
        internal static string Condition_100 {
            get {
                return ResourceManager.GetString("Condition_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads most barcodes reliably..
        /// </summary>
        internal static string Condition_105 {
            get {
                return ResourceManager.GetString("Condition_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads GS1 barcodes reliably..
        /// </summary>
        internal static string Condition_110 {
            get {
                return ResourceManager.GetString("Condition_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads GS1 barcodes reliably..
        /// </summary>
        internal static string Condition_115 {
            get {
                return ResourceManager.GetString("Condition_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner does not transmit AIM identifiers..
        /// </summary>
        internal static string Condition_200 {
            get {
                return ResourceManager.GetString("Condition_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on, but the letter casing is reported correctly..
        /// </summary>
        internal static string Condition_205 {
            get {
                return ResourceManager.GetString("Condition_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on, but the letter casing is preserved..
        /// </summary>
        internal static string Condition_206 {
            get {
                return ResourceManager.GetString("Condition_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        internal static string Condition_210 {
            get {
                return ResourceManager.GetString("Condition_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner does not transmit an end-of-line sequence..
        /// </summary>
        internal static string Condition_215 {
            get {
                return ResourceManager.GetString("Condition_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner transmits a prefix..
        /// </summary>
        internal static string Condition_220 {
            get {
                return ResourceManager.GetString("Condition_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner transmits a suffix..
        /// </summary>
        internal static string Condition_225 {
            get {
                return ResourceManager.GetString("Condition_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not read AIM identifier characters..
        /// </summary>
        internal static string Condition_230 {
            get {
                return ResourceManager.GetString("Condition_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read AIM identifier characters..
        /// </summary>
        internal static string Condition_231 {
            get {
                return ResourceManager.GetString("Condition_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may not transmit AIM identifiers..
        /// </summary>
        internal static string Condition_232 {
            get {
                return ResourceManager.GetString("Condition_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read the barcode type identifier..
        /// </summary>
        internal static string Condition_235 {
            get {
                return ResourceManager.GetString("Condition_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not be able to read Format 05 or Format 06 barcodes reliably..
        /// </summary>
        internal static string Condition_240 {
            get {
                return ResourceManager.GetString("Condition_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read Format 05 or Format 06 barcodes reliably..
        /// </summary>
        internal static string Condition_241 {
            get {
                return ResourceManager.GetString("Condition_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read Format 05 or Format 06 barcodes reliably..
        /// </summary>
        internal static string Condition_245 {
            get {
                return ResourceManager.GetString("Condition_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not test compatibility for compatibility with ISO/IEC 15434..
        /// </summary>
        internal static string Condition_250 {
            get {
                return ResourceManager.GetString("Condition_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data input performance is slower than expected..
        /// </summary>
        internal static string Condition_255 {
            get {
                return ResourceManager.GetString("Condition_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data input performance is very poor..
        /// </summary>
        internal static string Condition_256 {
            get {
                return ResourceManager.GetString("Condition_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain non-invariant characters..
        /// </summary>
        internal static string Condition_260 {
            get {
                return ResourceManager.GetString("Condition_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain non-invariant characters..
        /// </summary>
        internal static string Condition_261 {
            get {
                return ResourceManager.GetString("Condition_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain non-invariant characters..
        /// </summary>
        internal static string Condition_265 {
            get {
                return ResourceManager.GetString("Condition_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain data for Electronic Data Interchange (EDI).
        /// </summary>
        internal static string Condition_270 {
            get {
                return ResourceManager.GetString("Condition_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain data for Electronic Data Interchange (EDI).
        /// </summary>
        internal static string Condition_271 {
            get {
                return ResourceManager.GetString("Condition_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain data for Electronic Data Interchange (EDI).
        /// </summary>
        internal static string Condition_275 {
            get {
                return ResourceManager.GetString("Condition_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not read File Separator (ASCII 28) characters correctly..
        /// </summary>
        internal static string Condition_276 {
            get {
                return ResourceManager.GetString("Condition_276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read File Separator (ASCII 28) characters..
        /// </summary>
        internal static string Condition_277 {
            get {
                return ResourceManager.GetString("Condition_277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not read Unit Separator (ASCII 31) characters correctly..
        /// </summary>
        internal static string Condition_278 {
            get {
                return ResourceManager.GetString("Condition_278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read Unit Separator (ASCII 31) characters..
        /// </summary>
        internal static string Condition_279 {
            get {
                return ResourceManager.GetString("Condition_279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not read End-of-Transmission (ASCII 04) characters correctly..
        /// </summary>
        internal static string Condition_280 {
            get {
                return ResourceManager.GetString("Condition_280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read End-of-Transmission (ASCII 04) characters..
        /// </summary>
        internal static string Condition_281 {
            get {
                return ResourceManager.GetString("Condition_281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test failed..
        /// </summary>
        internal static string Condition_300 {
            get {
                return ResourceManager.GetString("Condition_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was reported for the barcode..
        /// </summary>
        internal static string Condition_301 {
            get {
                return ResourceManager.GetString("Condition_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data was not reported when you scanned the barcode..
        /// </summary>
        internal static string Condition_303 {
            get {
                return ResourceManager.GetString("Condition_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was reported for one or more barcodes..
        /// </summary>
        internal static string Condition_304 {
            get {
                return ResourceManager.GetString("Condition_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scanned a barcode out of sequence..
        /// </summary>
        internal static string Condition_305 {
            get {
                return ResourceManager.GetString("Condition_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data was not reported when you scanned one or more barcodes..
        /// </summary>
        internal static string Condition_306 {
            get {
                return ResourceManager.GetString("Condition_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner and computer have different keyboard layouts..
        /// </summary>
        internal static string Condition_307 {
            get {
                return ResourceManager.GetString("Condition_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner and computer have different keyboard layouts..
        /// </summary>
        internal static string Condition_308 {
            get {
                return ResourceManager.GetString("Condition_308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        internal static string Condition_309 {
            get {
                return ResourceManager.GetString("Condition_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        internal static string Condition_310 {
            get {
                return ResourceManager.GetString("Condition_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner and computer have different keyboard layouts..
        /// </summary>
        internal static string Condition_315 {
            get {
                return ResourceManager.GetString("Condition_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        internal static string Condition_316 {
            get {
                return ResourceManager.GetString("Condition_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcode characters reliably..
        /// </summary>
        internal static string Condition_320 {
            get {
                return ResourceManager.GetString("Condition_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        internal static string Condition_325 {
            get {
                return ResourceManager.GetString("Condition_325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        internal static string Condition_326 {
            get {
                return ResourceManager.GetString("Condition_326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to upper case..
        /// </summary>
        internal static string Condition_327 {
            get {
                return ResourceManager.GetString("Condition_327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to lower case..
        /// </summary>
        internal static string Condition_328 {
            get {
                return ResourceManager.GetString("Condition_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to simulate Caps Lock..
        /// </summary>
        internal static string Condition_330 {
            get {
                return ResourceManager.GetString("Condition_330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to upper case..
        /// </summary>
        internal static string Condition_331 {
            get {
                return ResourceManager.GetString("Condition_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to lower case..
        /// </summary>
        internal static string Condition_332 {
            get {
                return ResourceManager.GetString("Condition_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your keyboard layout supports {0} characters and cannot read barcodes reliably..
        /// </summary>
        internal static string Condition_335 {
            get {
                return ResourceManager.GetString("Condition_335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test failed unexpectedly..
        /// </summary>
        internal static string Condition_390 {
            get {
                return ResourceManager.GetString("Condition_390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, you did not test compatibility with ISO/IEC 15434. Your system may not be able to read barcodes reliably if they contain data formatted according to ISO/IEC 15434..
        /// </summary>
        internal static string Description_105 {
            get {
                return ResourceManager.GetString("Description_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, your verification software may not read barcodes reliably if the contain data formatted according to ISO/IEC 15434..
        /// </summary>
        internal static string Description_110 {
            get {
                return ResourceManager.GetString("Description_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, it cannot read barcodes reliably if the contain data formatted according to ISO/IEC 15434..
        /// </summary>
        internal static string Description_115 {
            get {
                return ResourceManager.GetString("Description_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your software may use them to eliminate unnecessary alerts..
        /// </summary>
        internal static string Description_200 {
            get {
                return ResourceManager.GetString("Description_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner is probably configured to compensate automatically for Caps Lock or to enter data using the numeric keypad (ALT mode)..
        /// </summary>
        internal static string Description_205 {
            get {
                return ResourceManager.GetString("Description_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Caps Lock key may be disabled or remapped. .
        /// </summary>
        internal static string Description_206 {
            get {
                return ResourceManager.GetString("Description_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, your computer keyboard layout is for a script that does not support upper- and lower-case letters..
        /// </summary>
        internal static string Description_210 {
            get {
                return ResourceManager.GetString("Description_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may slow your scanning performance. However, your software may not support end-of-line sequences..
        /// </summary>
        internal static string Description_215 {
            get {
                return ResourceManager.GetString("Description_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software may not recognise the prefix. .
        /// </summary>
        internal static string Description_220 {
            get {
                return ResourceManager.GetString("Description_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software may not recognise the suffix. .
        /// </summary>
        internal static string Description_225 {
            get {
                return ResourceManager.GetString("Description_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your software may use them to eliminate unnecessary alerts. However, the software must implement character mapping to read AIM identifiers reliably..
        /// </summary>
        internal static string Description_230 {
            get {
                return ResourceManager.GetString("Description_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your software may use them to eliminate unnecessary alerts..
        /// </summary>
        internal static string Description_231 {
            get {
                return ResourceManager.GetString("Description_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may transmit AIM identifiers, but this is not certain.  AIM identifiers represent the barcode type. Your software may use them to eliminate unnecessary alerts..
        /// </summary>
        internal static string Description_232 {
            get {
                return ResourceManager.GetString("Description_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your software may use them to eliminate unnecessary alerts..
        /// </summary>
        internal static string Description_235 {
            get {
                return ResourceManager.GetString("Description_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software must implement character mapping to read barcodes reliably if they contain non-invariant characters..
        /// </summary>
        internal static string Description_240 {
            get {
                return ResourceManager.GetString("Description_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        internal static string Description_245 {
            get {
                return ResourceManager.GetString("Description_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be a temporary or intermittent problem. Your computer may be busy, running a virus checker or a predictive text service. Your barcode scanner may be configured as a numeric keypad..
        /// </summary>
        internal static string Description_255 {
            get {
                return ResourceManager.GetString("Description_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be a temporary or intermittent problem. Your computer may be busy, running a virus checker or a predictive text service. Your barcode scanner may be configured as a numeric keypad..
        /// </summary>
        internal static string Description_256 {
            get {
                return ResourceManager.GetString("Description_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain non-invariant characters. Your software must implement character mapping to read these barcodes reliably..
        /// </summary>
        internal static string Description_260 {
            get {
                return ResourceManager.GetString("Description_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain non-invariant characters..
        /// </summary>
        internal static string Description_261 {
            get {
                return ResourceManager.GetString("Description_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain non-invariant characters..
        /// </summary>
        internal static string Description_265 {
            get {
                return ResourceManager.GetString("Description_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain EDI data. Your software must implement character mapping to read these barcodes reliably..
        /// </summary>
        internal static string Description_270 {
            get {
                return ResourceManager.GetString("Description_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain EDI data..
        /// </summary>
        internal static string Description_271 {
            get {
                return ResourceManager.GetString("Description_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain EDI data..
        /// </summary>
        internal static string Description_275 {
            get {
                return ResourceManager.GetString("Description_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These characters are not used widely in barcodes..
        /// </summary>
        internal static string Description_276 {
            get {
                return ResourceManager.GetString("Description_276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These characters are not used widely in barcodes..
        /// </summary>
        internal static string Description_277 {
            get {
                return ResourceManager.GetString("Description_277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These characters are not used widely in barcodes..
        /// </summary>
        internal static string Description_278 {
            get {
                return ResourceManager.GetString("Description_278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These characters are not used widely in barcodes..
        /// </summary>
        internal static string Description_279 {
            get {
                return ResourceManager.GetString("Description_279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcode types use this character to mark the end of barcode data. Your software may not correctly read any suffix added by the barcode scanner..
        /// </summary>
        internal static string Description_280 {
            get {
                return ResourceManager.GetString("Description_280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcode types use this character to mark the end of barcode data. Your software may not correctly read any suffix added by the barcode scanner..
        /// </summary>
        internal static string Description_281 {
            get {
                return ResourceManager.GetString("Description_281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have scanned a wrong barcode or entered incorrect data using the keyboard. Your barcode scanner or system may be slow, or some unexpected or intermittent issue may have occurred..
        /// </summary>
        internal static string Description_300 {
            get {
                return ResourceManager.GetString("Description_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts may not correspond. You may have scanned a wrong barcode or entered incorrect data using the keyboard. Your barcode scanner or system may be slow, or some unexpected or intermittent issue may have occurred..
        /// </summary>
        internal static string Description_303 {
            get {
                return ResourceManager.GetString("Description_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have scanned a wrong barcode or entered incorrect data using the keyboard. Your barcode scanner or system may be slow, or some unexpected or intermittent issue may have occurred..
        /// </summary>
        internal static string Description_306 {
            get {
                return ResourceManager.GetString("Description_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software must implement character mapping to read barcodes reliably..
        /// </summary>
        internal static string Description_307 {
            get {
                return ResourceManager.GetString("Description_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software may be able to compensate..
        /// </summary>
        internal static string Description_309 {
            get {
                return ResourceManager.GetString("Description_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software may be able to compensate. However, your system cannot read characters correctly for barcodes that contain Format 05 or Format 06 data. Some software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        internal static string Description_315 {
            get {
                return ResourceManager.GetString("Description_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software may be able to compensate. However, your system cannot read barcode characters correctly for barcodes that contain Format 05 or Format 06 data. Some software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        internal static string Description_316 {
            get {
                return ResourceManager.GetString("Description_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        internal static string Description_320 {
            get {
                return ResourceManager.GetString("Description_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Caps Lock is on, the default behaviour is to report all characters in upper-case..
        /// </summary>
        internal static string Description_326 {
            get {
                return ResourceManager.GetString("Description_326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcode characters reliably..
        /// </summary>
        internal static string Description_327 {
            get {
                return ResourceManager.GetString("Description_327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcode characters reliably..
        /// </summary>
        internal static string Description_328 {
            get {
                return ResourceManager.GetString("Description_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcode characters reliably..
        /// </summary>
        internal static string Description_331 {
            get {
                return ResourceManager.GetString("Description_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcode characters reliably..
        /// </summary>
        internal static string Description_332 {
            get {
                return ResourceManager.GetString("Description_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner or system may be slow or it may be affected by anti-virus software or some other unexpected or intermittent issue..
        /// </summary>
        internal static string Description_390 {
            get {
                return ResourceManager.GetString("Description_390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while resolving keyboard scripts: {0}.
        /// </summary>
        internal static string ErrorWhileResolvingKeyboardScripts {
            get {
                return ResourceManager.GetString("ErrorWhileResolvingKeyboardScripts", resourceCulture);
            }
        }
    }
}
