//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.BarcodeScanner.Calibration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.BarcodeScanner.Calibration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice items remaining mismatch..
        /// </summary>
        internal static string AdviceItemRemainingMismatch {
            get {
                return ResourceManager.GetString("AdviceItemRemainingMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix {0} does not match expected suffix {1}..
        /// </summary>
        internal static string Barcodes_Error_100 {
            get {
                return ResourceManager.GetString("Barcodes_Error_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect barcode provenance..
        /// </summary>
        internal static string CalibrateDeadKeyIncorrectBarcodeProvenance {
            get {
                return ResourceManager.GetString("CalibrateDeadKeyIncorrectBarcodeProvenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert space placeholders..
        /// </summary>
        internal static string Calibration_Error_001 {
            get {
                return ResourceManager.GetString("Calibration_Error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument provided to regular expression Replace method..
        /// </summary>
        internal static string Calibration_Error_002 {
            get {
                return ResourceManager.GetString("Calibration_Error_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regular expression timed out while performing a match..
        /// </summary>
        internal static string Calibration_Error_003 {
            get {
                return ResourceManager.GetString("Calibration_Error_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value for &apos;existing map&apos; key.
        /// </summary>
        internal static string Calibration_Error_004 {
            get {
                return ResourceManager.GetString("Calibration_Error_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect error information type..
        /// </summary>
        internal static string CalibrationIncorrectErrorInformationType {
            get {
                return ResourceManager.GetString("CalibrationIncorrectErrorInformationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect informational information type..
        /// </summary>
        internal static string CalibrationIncorrectInformationalInformationType {
            get {
                return ResourceManager.GetString("CalibrationIncorrectInformationalInformationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect warning information type..
        /// </summary>
        internal static string CalibrationIncorrectWarningInformationType {
            get {
                return ResourceManager.GetString("CalibrationIncorrectWarningInformationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers are supported..
        /// </summary>
        internal static string CalibrationInformation_130 {
            get {
                return ResourceManager.GetString("CalibrationInformation_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is transmitting an AIM identifier: {0}.
        /// </summary>
        internal static string CalibrationInformation_131 {
            get {
                return ResourceManager.GetString("CalibrationInformation_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner may be transmitting an AIM identifier: {0}.
        /// </summary>
        internal static string CalibrationInformation_132 {
            get {
                return ResourceManager.GetString("CalibrationInformation_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is transmitting an end-of-line character sequence: {0}.
        /// </summary>
        internal static string CalibrationInformation_150 {
            get {
                return ResourceManager.GetString("CalibrationInformation_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Separator characters are supported..
        /// </summary>
        internal static string CalibrationInformation_160 {
            get {
                return ResourceManager.GetString("CalibrationInformation_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Separator characters are supported..
        /// </summary>
        internal static string CalibrationInformation_161 {
            get {
                return ResourceManager.GetString("CalibrationInformation_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File separator characters are supported..
        /// </summary>
        internal static string CalibrationInformation_162 {
            get {
                return ResourceManager.GetString("CalibrationInformation_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit separator characters are supported..
        /// </summary>
        internal static string CalibrationInformation_163 {
            get {
                return ResourceManager.GetString("CalibrationInformation_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-of-Transmission characters are supported..
        /// </summary>
        internal static string CalibrationInformation_164 {
            get {
                return ResourceManager.GetString("CalibrationInformation_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character for an invariant character is the same as the character reported for the End-of-Transmission character..
        /// </summary>
        internal static string CalibrationInformation_165 {
            get {
                return ResourceManager.GetString("CalibrationInformation_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner may be configured to compensate for Caps Lock..
        /// </summary>
        internal static string CalibrationInformation_170 {
            get {
                return ResourceManager.GetString("CalibrationInformation_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer keyboard supports the following script: {0}.
        /// </summary>
        internal static string CalibrationInformation_180 {
            get {
                return ResourceManager.GetString("CalibrationInformation_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer keyboard is configured for the following platform: {0}.
        /// </summary>
        internal static string CalibrationInformation_190 {
            get {
                return ResourceManager.GetString("CalibrationInformation_190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some non-invariant ASCII characters cannot be detected..
        /// </summary>
        internal static string CalibrationInformation_200 {
            get {
                return ResourceManager.GetString("CalibrationInformation_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some non-invariant ASCII characters are not recognised: {0}.
        /// </summary>
        internal static string CalibrationInformation_201 {
            get {
                return ResourceManager.GetString("CalibrationInformation_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some combinations of non-invariant ASCII characters are not recognised: {0}.
        /// </summary>
        internal static string CalibrationInformation_202 {
            get {
                return ResourceManager.GetString("CalibrationInformation_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodes that use ISO/IEC 15434 syntax cannot be recognised..
        /// </summary>
        internal static string CalibrationInformation_210 {
            get {
                return ResourceManager.GetString("CalibrationInformation_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodes that use ISO/IEC 15434 syntax to represent EDI data cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_211 {
            get {
                return ResourceManager.GetString("CalibrationInformation_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The group separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_212 {
            get {
                return ResourceManager.GetString("CalibrationInformation_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record separator character cannot be read..
        /// </summary>
        internal static string CalibrationInformation_213 {
            get {
                return ResourceManager.GetString("CalibrationInformation_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The record separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_214 {
            get {
                return ResourceManager.GetString("CalibrationInformation_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The record separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_215 {
            get {
                return ResourceManager.GetString("CalibrationInformation_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file separator character cannot be read..
        /// </summary>
        internal static string CalibrationInformation_216 {
            get {
                return ResourceManager.GetString("CalibrationInformation_216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_217 {
            get {
                return ResourceManager.GetString("CalibrationInformation_217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The file separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_218 {
            get {
                return ResourceManager.GetString("CalibrationInformation_218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The file separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_219 {
            get {
                return ResourceManager.GetString("CalibrationInformation_219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit separator character cannot be read..
        /// </summary>
        internal static string CalibrationInformation_220 {
            get {
                return ResourceManager.GetString("CalibrationInformation_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_221 {
            get {
                return ResourceManager.GetString("CalibrationInformation_221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The unit separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_222 {
            get {
                return ResourceManager.GetString("CalibrationInformation_222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The unit separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_223 {
            get {
                return ResourceManager.GetString("CalibrationInformation_223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end-of-transmission character cannot be read..
        /// </summary>
        internal static string CalibrationInformation_224 {
            get {
                return ResourceManager.GetString("CalibrationInformation_224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end-of-transmission character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_225 {
            get {
                return ResourceManager.GetString("CalibrationInformation_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The end-of-transmission character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_226 {
            get {
                return ResourceManager.GetString("CalibrationInformation_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The end-of-transmission character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_227 {
            get {
                return ResourceManager.GetString("CalibrationInformation_227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is not transmitting an AIM Identifier..
        /// </summary>
        internal static string CalibrationInformation_230 {
            get {
                return ResourceManager.GetString("CalibrationInformation_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AIM Identifier cannot be recognised..
        /// </summary>
        internal static string CalibrationInformation_231 {
            get {
                return ResourceManager.GetString("CalibrationInformation_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AIM identifier cannot be read reliably..
        /// </summary>
        internal static string CalibrationInformation_232 {
            get {
                return ResourceManager.GetString("CalibrationInformation_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is transmitting a prefix: {0}.
        /// </summary>
        internal static string CalibrationInformation_240 {
            get {
                return ResourceManager.GetString("CalibrationInformation_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is transmitting a code: {0}.
        /// </summary>
        internal static string CalibrationInformation_241 {
            get {
                return ResourceManager.GetString("CalibrationInformation_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is transmitting a suffix: {0}.
        /// </summary>
        internal static string CalibrationInformation_242 {
            get {
                return ResourceManager.GetString("CalibrationInformation_242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner is not transmitting an end-of-line character sequence (e.g. a carriage return)..
        /// </summary>
        internal static string CalibrationInformation_245 {
            get {
                return ResourceManager.GetString("CalibrationInformation_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} is ambiguous. There are multiple keys for the same character, each representing a different expected character. However, at most, only one of the expected characters is invariant..
        /// </summary>
        internal static string CalibrationInformation_250 {
            get {
                return ResourceManager.GetString("CalibrationInformation_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some reported characters are ambiguous. There are multiple keys for the same character, each representing a different non-invariant expected ASCII character: {0}.
        /// </summary>
        internal static string CalibrationInformation_251 {
            get {
                return ResourceManager.GetString("CalibrationInformation_251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM Identifiers cannot be recognised. The reported character {0} is ambiguous. There are multiple keys for this character which represents the AIM flag character as well as other expected character(s)..
        /// </summary>
        internal static string CalibrationInformation_252 {
            get {
                return ResourceManager.GetString("CalibrationInformation_252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some reported non-invariant ASCII characters are ambiguous: {0}.
        /// </summary>
        internal static string CalibrationInformation_253 {
            get {
                return ResourceManager.GetString("CalibrationInformation_253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} for a File Separator is ambiguous. Barcodes that use ISO/IEC 15434 syntax to represent EDI data cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_254 {
            get {
                return ResourceManager.GetString("CalibrationInformation_254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} for a Unit Separator is ambiguous. Barcodes that use ISO/IEC 15434 syntax to represent EDI data cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_255 {
            get {
                return ResourceManager.GetString("CalibrationInformation_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} for an End-of-Transmission character is ambiguous. Barcodes that use ISO/IEC 15434 syntax cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_256 {
            get {
                return ResourceManager.GetString("CalibrationInformation_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some reported character sequences are ambiguous. These characters do not represent invariant characters: {0}.
        /// </summary>
        internal static string CalibrationInformation_257 {
            get {
                return ResourceManager.GetString("CalibrationInformation_257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. This may prevent reading of any additional data elements included in a barcode..
        /// </summary>
        internal static string CalibrationInformation_258 {
            get {
                return ResourceManager.GetString("CalibrationInformation_258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} for a File Separator is ambiguous. Barcodes that use ASCII 28 control characters may not be reliably read..
        /// </summary>
        internal static string CalibrationInformation_259 {
            get {
                return ResourceManager.GetString("CalibrationInformation_259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} for a Unit Separator is ambiguous. Barcodes that use ASCII 31 control characters may not be reliably read..
        /// </summary>
        internal static string CalibrationInformation_260 {
            get {
                return ResourceManager.GetString("CalibrationInformation_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} for an End-of-Transmission character is ambiguous. Barcodes that use ASCII04 control characters may not be reliably read..
        /// </summary>
        internal static string CalibrationInformation_261 {
            get {
                return ResourceManager.GetString("CalibrationInformation_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. This represents the record separator character..
        /// </summary>
        internal static string CalibrationInformation_262 {
            get {
                return ResourceManager.GetString("CalibrationInformation_262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond..
        /// </summary>
        internal static string CalibrationInformation_270 {
            get {
                return ResourceManager.GetString("CalibrationInformation_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond for invariant characters..
        /// </summary>
        internal static string CalibrationInformation_271 {
            get {
                return ResourceManager.GetString("CalibrationInformation_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond for non-invariant ASCII characters..
        /// </summary>
        internal static string CalibrationInformation_272 {
            get {
                return ResourceManager.GetString("CalibrationInformation_272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond when representing File Separators..
        /// </summary>
        internal static string CalibrationInformation_273 {
            get {
                return ResourceManager.GetString("CalibrationInformation_273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond when representing Group Separators..
        /// </summary>
        internal static string CalibrationInformation_274 {
            get {
                return ResourceManager.GetString("CalibrationInformation_274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond when representing Record Separators..
        /// </summary>
        internal static string CalibrationInformation_275 {
            get {
                return ResourceManager.GetString("CalibrationInformation_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond when representing Unit Separators..
        /// </summary>
        internal static string CalibrationInformation_276 {
            get {
                return ResourceManager.GetString("CalibrationInformation_276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond when representing End-of-Transmission characters..
        /// </summary>
        internal static string CalibrationInformation_277 {
            get {
                return ResourceManager.GetString("CalibrationInformation_277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts do not correspond when representing AIM identifiers..
        /// </summary>
        internal static string CalibrationInformation_278 {
            get {
                return ResourceManager.GetString("CalibrationInformation_278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correspondence of the barcode scanner and computer keyboard layouts cannot be determined..
        /// </summary>
        internal static string CalibrationInformation_279 {
            get {
                return ResourceManager.GetString("CalibrationInformation_279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        internal static string CalibrationInformation_280 {
            get {
                return ResourceManager.GetString("CalibrationInformation_280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock may be switched on..
        /// </summary>
        internal static string CalibrationInformation_281 {
            get {
                return ResourceManager.GetString("CalibrationInformation_281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner may be configured to convert characters to upper case..
        /// </summary>
        internal static string CalibrationInformation_282 {
            get {
                return ResourceManager.GetString("CalibrationInformation_282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner may be configured to convert characters to lower case..
        /// </summary>
        internal static string CalibrationInformation_283 {
            get {
                return ResourceManager.GetString("CalibrationInformation_283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner may be configured to invert character case..
        /// </summary>
        internal static string CalibrationInformation_284 {
            get {
                return ResourceManager.GetString("CalibrationInformation_284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best reported keyboard data entry time during calibration indicates that the barcode scanner does not perform optimally..
        /// </summary>
        internal static string CalibrationInformation_290 {
            get {
                return ResourceManager.GetString("CalibrationInformation_290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No calibration data was reported..
        /// </summary>
        internal static string CalibrationInformation_300 {
            get {
                return ResourceManager.GetString("CalibrationInformation_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported data is unrecognised. The wrong barcode may have been scanned..
        /// </summary>
        internal static string CalibrationInformation_301 {
            get {
                return ResourceManager.GetString("CalibrationInformation_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters detected. The wrong barcode may have been scanned..
        /// </summary>
        internal static string CalibrationInformation_302 {
            get {
                return ResourceManager.GetString("CalibrationInformation_302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial data was reported for calibration barcode..
        /// </summary>
        internal static string CalibrationInformation_303 {
            get {
                return ResourceManager.GetString("CalibrationInformation_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported data is for the wrong calibration barcode..
        /// </summary>
        internal static string CalibrationInformation_304 {
            get {
                return ResourceManager.GetString("CalibrationInformation_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to calibrate a barcode, but no calibration token was provided..
        /// </summary>
        internal static string CalibrationInformation_305 {
            get {
                return ResourceManager.GetString("CalibrationInformation_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some invariant characters cannot be detected..
        /// </summary>
        internal static string CalibrationInformation_310 {
            get {
                return ResourceManager.GetString("CalibrationInformation_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some invariant characters are not recognised by the barcode scanner in its current configuration: {0}.
        /// </summary>
        internal static string CalibrationInformation_311 {
            get {
                return ResourceManager.GetString("CalibrationInformation_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some key combinations that include invariant characters are not recognised: {0}.
        /// </summary>
        internal static string CalibrationInformation_312 {
            get {
                return ResourceManager.GetString("CalibrationInformation_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group separator is reported..
        /// </summary>
        internal static string CalibrationInformation_320 {
            get {
                return ResourceManager.GetString("CalibrationInformation_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} is ambiguous. There are multiple keys for the same character, each representing a different expected character..
        /// </summary>
        internal static string CalibrationInformation_360 {
            get {
                return ResourceManager.GetString("CalibrationInformation_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character {0} is ambiguous. The same character is reported for multiple dead key sequences representing different expected characters..
        /// </summary>
        internal static string CalibrationInformation_361 {
            get {
                return ResourceManager.GetString("CalibrationInformation_361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported dead key character {0} is ambiguous. There are multiple dead keys for the same character, each representing a different expected character..
        /// </summary>
        internal static string CalibrationInformation_362 {
            get {
                return ResourceManager.GetString("CalibrationInformation_362", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The same sequence is reported for multiple expected character sequences..
        /// </summary>
        internal static string CalibrationInformation_363 {
            get {
                return ResourceManager.GetString("CalibrationInformation_363", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The same sequence is reported for multiple dead keys in the barcode scanner&apos;s keyboard layout..
        /// </summary>
        internal static string CalibrationInformation_364 {
            get {
                return ResourceManager.GetString("CalibrationInformation_364", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character {0} cannot be represented reliably because of incompatibility with the keyboard layout..
        /// </summary>
        internal static string CalibrationInformation_365 {
            get {
                return ResourceManager.GetString("CalibrationInformation_365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group separator character cannot be read..
        /// </summary>
        internal static string CalibrationInformation_366 {
            get {
                return ResourceManager.GetString("CalibrationInformation_366", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported character sequence {0} is ambiguous. The group separator character cannot be reliably read..
        /// </summary>
        internal static string CalibrationInformation_367 {
            get {
                return ResourceManager.GetString("CalibrationInformation_367", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some reported characters are ambiguous. They can be reported individually but are also used to compose ligatures: {0}.
        /// </summary>
        internal static string CalibrationInformation_368 {
            get {
                return ResourceManager.GetString("CalibrationInformation_368", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported calibration data cannot be processed. It does not include expected delimiters..
        /// </summary>
        internal static string CalibrationInformation_370 {
            get {
                return ResourceManager.GetString("CalibrationInformation_370", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported calibration data cannot be processed. No character can be determined to act as a temporary delimiter..
        /// </summary>
        internal static string CalibrationInformation_371 {
            get {
                return ResourceManager.GetString("CalibrationInformation_371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration failed. {0}.
        /// </summary>
        internal static string CalibrationInformation_390 {
            get {
                return ResourceManager.GetString("CalibrationInformation_390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration failed. {0}.
        /// </summary>
        internal static string CalibrationInformation_391 {
            get {
                return ResourceManager.GetString("CalibrationInformation_391", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid advice item..
        /// </summary>
        internal static string CalibrationInvalidAdviceItem {
            get {
                return ResourceManager.GetString("CalibrationInvalidAdviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid information level..
        /// </summary>
        internal static string CalibrationInvalidInformationLevel {
            get {
                return ResourceManager.GetString("CalibrationInvalidInformationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unspecified.
        /// </summary>
        internal static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find suitable character for temporary placeholder. All extended ASCII characters are already used in the input string..
        /// </summary>
        internal static string UnusedExtendedAsciiCharacterNotFound {
            get {
                return ResourceManager.GetString("UnusedExtendedAsciiCharacterNotFound", resourceCulture);
            }
        }
    }
}
